version: '3.4'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development,
      DATABASE_HOST: 'db'
    ports:
      - 3000:3000
    depends_on: 
      - db
  
  db:
    image: postgres
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DATABASE: student
    ports:
      - 5434:5432
